spring:
  application:
    name : health-tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/health_tracker
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: health_tracker
    validate-migration-naming: true
    out-of-order: true

  jpa:
    hibernate:
      ddl-auto: validate

  graphql:
    graphiql:
      enabled: true
      path: /graphiql
      endpoint: /graphql

jwt:
  secret: n6atHayIpvmTjUXRLEYMTf621jR+vdg1y0wukgnn1h8=
  expiration: 86400000 # 24 hours in milliseconds
